name: "Tar Action for Vixen-js Projects"
description: "Cross platform github action to tar files"
branding:
  icon: "box"
  color: "green"
inputs:
  cwd:
    description: "Directory to tar command"
    required: false
  command:
    description: "compress"
    required: true
  files:
    description: "List of files to archive"
    required: true
  outPath:
    description: "Output path"
    required: true
outputs:
  done:
    description: "Returns 1 if all files are archived"
runs:
  using: "node20"
  main: "action.js"
